export const MILLISECONDS_IN_SECOND = 1000;
export const MILLISECONDS_IN_MINUTE = MILLISECONDS_IN_SECOND * 60;
export const MILLISECONDS_IN_ONE_HOUR = MILLISECONDS_IN_MINUTE * 60;
export const MILLISECONDS_IN_DAY = MILLISECONDS_IN_ONE_HOUR * 24;

export const SECONDS_IN_DAY = MILLISECONDS_IN_DAY / 1000;

export const MINUTE = 1;
export const MIN_IN_HOUR = 60;
export const MIN_IN_DAY = MIN_IN_HOUR * 24;
export const MIN_IN_MONTH = MIN_IN_DAY * 30;
